multimedia: add RPROVIDES for multimedia kernel modules
Add the multimedia acceleration kernel modules to the RPROVIDES variable of the
appropriate recipes. This fixes build errors of the following form at do_roofs time
when RPM packaging is used:
error: Can't install <foo>@MACHINE: no package provides <bar>

Thank you to Tadao Tanikawa for his work on this within AGL [1]
[1] https://gerrit.automotivelinux.org/gerrit/#/c/4061/1