rcar-gen2: omx-user-module: Fix build error by .la files
The following errors occurs in latest Poky (master branch).

ERROR: QA Issue: libomxr_XXXX.la failed sanity test (workdir) ...

In latest Poky, new class "remove-libtool" was added.
This patch uses remove-libtool class for delete .la files.

Signed-off-by: Takeshi Saito <takeshi.saito.xv@renesas.com>
(cherry picked from commit 73123be306549ebbf49447d82cd16ec0cae09b68)