multimedia: fix "no package provides kernel-module-vsp2"
The kernel VSP2 driver was missed from commit c4b85e1 which
added RPROVIDES for the multimedia acceleration kernel modules.
Correct that now, which fixes build errors of the following
form at do_rootfs time when RPM packaging is used:
error: Can't install <foo>@MACHINE: no package provides <bar>

For example:
error: Can't install vsp2-kernel-module-1.0-r0@porter: no package provides kernel-module-vsp2