rcar-gen2: conf: gcc version is fixed to 4.9
In Poky(YP1.9), the version of gcc was set to 5.2 as the default.
title : tcmode-default: Set gcc 5.2 as the default
commit: 3d81a56912fb2c6ca1c5aafb93cbc6e2cfea20b3
Author: Richard Purdie <richard.purdie@linuxfoundation.org>

Renesas BSP kernel(3.10.31-ltsi) is not supporting gcc-5.x.
Therefore, the following errors occur.

fatal error: linux/compiler-gcc5.h: No such file or directory

This patch sets the version of gcc to 4.9.

Signed-off-by: Takeshi Saito <takeshi.saito.xv@renesas.com>
(cherry picked from commit 8010a5dd3ba8d01c6aa671318e36d4cc7ee4ea2a)